### ISSUE TITLE
YAML-LD-star

### ISSUE THREAD

**Issue by VladimirAlexiev** [json-ld/yaml-ld#45]
As an information architect.
I want to be able to represent embedded triples and annotations.
So that I can reap the benefits of RDF-star in YAML (YAML-LD-star).

Given the JSON-LD-star effort https://json-ld.github.io/json-ld-star/, I think YAML-LD should support the same.

Examples from that spec can be translated to YAML in a straight-forward way. 
Notes:
- Ex 8 & 9 are omitted
- There are more examples in https://json-ld.github.io/json-ld-star/tests/
- Using `$` instead of `@` to avoid quotes
- Contexts omitted for brevity in many cases

Turtle-star example 3
```ttl
<< :bob :age 42 >> :certainty 0.8 .
```
YAML-LD-star example 3:
```yaml
$id:
  $id: bob
  age: 42
certainty: 0.8
```
YAML-LD-star example 4:
```yaml
$id:
  $id: bob
  age: 
    $value: 42
    $annotation:
      certainty: 0.8
```

Turtle-star example 5
```ttl
:alice :claims << :bob :knows :alice >> .
```
YAML-LD-star example 5:
```yaml
  $context:
    $base: http://example.org/
    $vocab: http://example.org/
    knows: {$type: $id}
    claimedBy: {$reverse: http://example.org/claims, $type: $id}
  $id:
    $id: bob
    knows: alice
  claimedBy: alice
```

Turtle-star example 6
```ttl
:bob :knows :alice .
<< :bob :knows :alice >> :accordingTo :alice .
:bob :claims << :bob :knows :alice >> .
```
YAML-LD-star example 6
```yaml
  $id: bob
  knows:
    $id: alice
    $annotation:
      accordingTo: alice
      claimedBy: bob
```

Turtle-star example 7
```ttl
<< :bob :knows :alice >> :certainty 0.8e .
<< << :bob :knows :alice >> :certainty 0.8e >> :claims :ted .
```

YAML-LD-star example 7
```yaml
  $id:
    $id: bob
    knows: {$id: alice}
  certainty: {
    $value: 0.8,
    $annotation: {claims: ted}
```

---

But there is a more YAMLish way to represent these examples:
In YAML, keys may be arbitrary nodes, so example 3 can be represented like this in flow style:
YAML-LD example 3F:
```yaml
{$id: bob, age: 42}: certainty: 0.8
```
And like this in block style:
YAML-LD example 3B:
```yaml
? $id: bob
  age: 42
: certainty: 0.8
```

Example 7F:
```yaml
  {{$id: bob, knows: {$id: alice}}: certainty: 0.8}: {claims: ted}
```

**Comment by gkellogg** [comment]
Presumably, YAML-LD should not require anything specific to support -star; it should follow from the generalized support for JSON-LD representation in YAML. Being too explicit would require regular maintenance of YAML-LD to follow. Better figure out how to establish principles for representing JSON-LD in YAML without getting into each individual feature defined in JSON-LD, JSON-LD-star, or whatever else we may come up with.

**Comment by VladimirAlexiev** [comment]
@gkellogg 
Because YAML doesn't have the JSON restriction that keys must be strings, it offers a much more natural way to represent RDF-star data.

We all agree that the default route (JSON-LD->YAML-LD using the standard conversion JSON->YAML) is the base case (and an important one).

The default conversion will make `YAML-LD-star example 3`. 
```yaml
$id:
  $id: bob
  age: 42
certainty: 0.8
```
But `YAML-LD example 3F` is much nicer (easier on the eyes and easier to understand):
```yaml
{$id: bob, age: 42}: certainty: 0.8
```

So Gregg, do you vote for or against this UCR?
